version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - noctx
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    depguard:
      rules:
        aws-sdk-v1:
          list-mode: lax
          allow:
            - github.com/aws/aws-sdk-go-v2
          deny:
            - pkg: github.com/aws/aws-sdk-go
        logger:
          files:
            - '!**/pkg/logutils/**.go'
          deny:
            - pkg: github.com/sirupsen/logrus
            - pkg: github.com/pkg/errors
            - pkg: github.com/instana/testify
    dupl:
      threshold: 100
    errcheck:
      exclude-functions:
        - (*github.com/infralight/go-kit/flycontext.Error).Msg
    errorlint:
      asserts: false
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-checks:
        - ifElseChain
      settings:
        ifElseChain:
          minThreshold: 1
    govet:
      enable:
        - nilness
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: US
      ignore-rules:
        - importas
    mnd:
      ignored-functions:
        - strings.SplitN
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocritic
          - lll
        path: (.+)_test\.go
      - linters:
          - dupl
        path: pkg/golinters
      - linters:
          - gocritic
          - lll
        path: components/orchestrator-api/pkg/server/handlers.go
      - linters:
          - unused
        path: components/orchestrator-api/pkg/server/middleware.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/infralight
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
