linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/infralight/go-kit/flycontext.Error).Msg
  depguard:
    rules:
      logger:
        deny:
          - pkg: "github.com/sirupsen/logrus"
          - pkg: "github.com/pkg/errors"
          - pkg: "github.com/instana/testify"
        files:
          - "!**/pkg/logutils/**.go"
  dupl:
    threshold: 100
  funlen:
    lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  goimports:
    local-prefixes: github.com/infralight
  mnd:
    ignored-functions:
      - strings.SplitN
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    enable:
      - nilness
      - shadow
  errorlint:
    asserts: false
  lll:
    line-length: 140
  misspell:
    locale: US
    ignore-words:
      - "importas" # linter name
  gocritic:
    enabled-checks:
      - ifElseChain
    settings:
      ifElseChain:
        minThreshold: 1  # Flag any use of else
linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    #    - goprintffuncname
    - gosec
    #    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    #    - nakedret
    - noctx
    # - nolintlint
    #    - revive
    - staticcheck
    #    - stylecheck
    #    - testifylint
    - unconvert
    - unparam
    - unused
  #    - whitespace


issues:
  exclude-rules:
    - path: (.+)_test\.go
      linters:
        - dupl
        - lll
        - gocritic

    # The logic of creating a linter is similar between linters, it's not duplication.
    - path: pkg/golinters
      linters:
        - dupl

    - path: components/orchestrator-api/pkg/server/handlers.go
      linters:
        - lll
        - gocritic

    - path: components/orchestrator-api/pkg/server/middleware.go
      linters:
        - unused