{{- if .Values.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-role
rules:
  - apiGroups:
      - '*'
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
      - configmaps
{{- end -}}
