{{- if .Values.credentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
type: Opaque
data:
  IACATHON_TFC_TOKEN: {{ .Values.credentials.tfcToken | b64enc }}
  {{- if .Values.credentials.tfcCustomDomain }}
  IACATHON_TFC_CUSTOM_DOMAIN: {{ .Values.credentials.tfcCustomDomain | b64enc }}
  {{- end }}
{{- end }}
