apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
type: Opaque
data:
  IACATHON_TFC_TOKEN: {{ .Values.credentials.IACATHON_TFC_TOKEN | b64enc }}
  {{- if .Values.credentials.IACATHON_TFC_CUSTOM_DOMAIN }}
  IACATHON_TFC_CUSTOM_DOMAIN: {{ .Values.credentials.IACATHON_TFC_CUSTOM_DOMAIN | b64enc }}
  {{- end }}
