{{- if .Values.credentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretNameOverride | default (printf "%s-credentials" .Release.Name) }}
type: Opaque
data:
  { { - if .Values.tfcCustomDomain } }
  IACATHON_TFC_TOKEN: {{ .Values.credentials.tfcToken | b64enc }}
  { { - end } }
  { { - if .Values.argocdDomain } }
  IACATHON_ARGOCD_TOKEN: {{ .Values.credentials.argocdToken | b64enc }}
  { { - end } }
  {{- end }}
