apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
type: Opaque
data:
  tfcToken: {{ .Values.credentials.tfcToken | b64enc }}
  {{- if .Values.credentials.tfcCustomDomain }}
  tfcCustomDomain: {{ .Values.credentials.tfcCustomDomain | b64enc }}
  {{- end }}
