name: Dockerhub

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
    inputs:
      collectortag:
        description: 'tag?'
        required: true
        default: 'latest'

env:
  TEST_TYPE: 'images'
  TERRAFORM_PROVIDERS_FOLDER: '${{ github.workspace }}/providers'
  GITLEAKS_CONFIG_PATH: '${{ github.workspace }}/gitleaks.toml'

jobs:
  dockerhub-build:
    name: Build and push dockerhub
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Build and push image to prod
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          infralightio/self-hosted-redactor:${{ github.event.inputs.collectortag }}
          infralightio/self-hosted-redactor:latest
        labels: |
          org.opencontainers.image.created=${{ steps.current-time.outputs.time }}
          org.opencontainers.image.authors=Infralight
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.version=${{ github.event.inputs.collectortag }}
