name: Release CF Template
on:
  workflow_dispatch:
jobs:
  CI:
    env:
      S3_BUCKET_CLI: infralight-templates-public
      AWS_REGION: us-east-1
    name: "Cloudformation Templates Release"
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Upload ECS Cloudformation Template
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --exclude='*' --include='template.yml'
      env:
        SOURCE_DIR: 'cloudformation/ecs'
        DEST_DIR: 'states-redactor/ecs'
        AWS_S3_BUCKET: ${{ env.S3_BUCKET_CLI }}
